config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "download" => "pages#download"
  get "contact" => "pages#contact"
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def download 
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Postboxing", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Download", download_path %></li>
        <% if user_signed_in?%>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %> 
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        <% if user_signed_in?%>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postboxing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<%= render "layouts/header" %>
	<div class="container">
		<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We are working on the One Month Rails Test App for Postboxing</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>We may be working to bring the snail mail to you more efficiently, but that doesn't mean we don't like the emails.</p>
<p>We LOVE to hear from you guys. Shout out at us and send us some love. You can email us at <%= mail_to "email", "drw.pia@gmail.com" %> anytime! </p>

app/views/pages/download.html.erb
<h1>Download</h1>
<p>You can download the postboxing app for Android <%= link_to "here", "https://play.google.com/store?hl=en" %>! </p>
<p>Once you download the app, take a few minutes to set up a profile, and before you know it you'll have your packages delivered to, basically, your front door. Shopping online just got made a lot easier! </p>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to Postboxing!</h1>
	<% if user_signed_in?%>
		<p> Thanks for stopping by! We are currently in beta version and getting ready to launch in Brooklyn, NYC very soon! Stay tuned for further updates on our services and expansion to your own city and neighborhood. <p>
		<p> We're really looking forward to getting you on board so you can start getting your online purchases delivered at a time that is convenient for you! <p>
	<% else %>
		<p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-warning btn-lg" %> to get your packages delivered to the corner store!<p>
	<% end %>
<div>